// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmA-5xXFUnU5wh0qyIDS8lSEWj8mOeSc',
    appId: '1:169016571396:web:6ac37b5c3136f7b1f9a751',
    messagingSenderId: '169016571396',
    projectId: 'fddassignment-c9283',
    authDomain: 'fddassignment-c9283.firebaseapp.com',
    databaseURL: 'https://fddassignment-c9283-default-rtdb.firebaseio.com',
    storageBucket: 'fddassignment-c9283.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMBaj6gHf1sey6GvL_TR-hQiPUlPlw8A',
    appId: '1:169016571396:android:1bb4692d8d224288f9a751',
    messagingSenderId: '169016571396',
    projectId: 'fddassignment-c9283',
    databaseURL: 'https://fddassignment-c9283-default-rtdb.firebaseio.com',
    storageBucket: 'fddassignment-c9283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD350ksDS5B2sVRBpvvUfRSvCx9kK1Vmm8',
    appId: '1:169016571396:ios:acd0192a08c6a7fff9a751',
    messagingSenderId: '169016571396',
    projectId: 'fddassignment-c9283',
    databaseURL: 'https://fddassignment-c9283-default-rtdb.firebaseio.com',
    storageBucket: 'fddassignment-c9283.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD350ksDS5B2sVRBpvvUfRSvCx9kK1Vmm8',
    appId: '1:169016571396:ios:acd0192a08c6a7fff9a751',
    messagingSenderId: '169016571396',
    projectId: 'fddassignment-c9283',
    databaseURL: 'https://fddassignment-c9283-default-rtdb.firebaseio.com',
    storageBucket: 'fddassignment-c9283.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmA-5xXFUnU5wh0qyIDS8lSEWj8mOeSc',
    appId: '1:169016571396:web:b6efc9c21e7e7b4ff9a751',
    messagingSenderId: '169016571396',
    projectId: 'fddassignment-c9283',
    authDomain: 'fddassignment-c9283.firebaseapp.com',
    databaseURL: 'https://fddassignment-c9283-default-rtdb.firebaseio.com',
    storageBucket: 'fddassignment-c9283.firebasestorage.app',
  );

}