// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWG4BwLQp8LF4vawBZ1IQ7RP8WNnLtRdM',
    appId: '1:161439195735:web:871f6e0996db3195813912',
    messagingSenderId: '161439195735',
    projectId: 'apevent-group9',
    authDomain: 'apevent-group9.firebaseapp.com',
    storageBucket: 'apevent-group9.firebasestorage.app',
    measurementId: 'G-3SV1ZK5MS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62RGhFn8LaohNtCptsA2mFHR1CSRnjJI',
    appId: '1:161439195735:android:771495dccb7f4f51813912',
    messagingSenderId: '161439195735',
    projectId: 'apevent-group9',
    storageBucket: 'apevent-group9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-rzbaeVLnp8If5kDb_mS-ofD4UvUEew',
    appId: '1:161439195735:ios:800608e5954993f3813912',
    messagingSenderId: '161439195735',
    projectId: 'apevent-group9',
    storageBucket: 'apevent-group9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAssignment',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-rzbaeVLnp8If5kDb_mS-ofD4UvUEew',
    appId: '1:161439195735:ios:800608e5954993f3813912',
    messagingSenderId: '161439195735',
    projectId: 'apevent-group9',
    storageBucket: 'apevent-group9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWG4BwLQp8LF4vawBZ1IQ7RP8WNnLtRdM',
    appId: '1:161439195735:web:eaf5f47ad467e417813912',
    messagingSenderId: '161439195735',
    projectId: 'apevent-group9',
    authDomain: 'apevent-group9.firebaseapp.com',
    storageBucket: 'apevent-group9.firebasestorage.app',
    measurementId: 'G-X7QSEKZG5X',
  );
}
